import { useMemo, useState } from 'react'
import type { FormEvent } from 'react'
import './App.css'

type Log = { date: string; weight: number }
type Workout = { date: string; name: string; exercises: number; volume: number }

const plans = {
  '3-day full body': ['Squat or leg press', 'Bench press', 'Row', 'Romanian deadlift', 'Overhead press', 'Lat pulldown'],
  '4-day upper/lower': ['Upper A: bench, row, shoulder press', 'Lower A: squat, RDL, calves', 'Upper B: incline press, pulldown, arms', 'Lower B: deadlift, split squat, hamstrings'],
  '5-day push/pull/legs': ['Push: chest, shoulders, triceps', 'Pull: back, rear delts, biceps', 'Legs: quads, hamstrings, calves', 'Upper: strength focus', 'Lower: volume focus'],
}

const beginnerRules = [
  ['Train 3 days', 'Leave at least one rest day between full-body sessions.'],
  ['Use clean reps', 'Stop with 1–3 reps still in reserve; do not chase failure every set.'],
  ['Progress slowly', 'Add 1–2 reps first, then the smallest weight increase when all sets feel solid.'],
  ['Recover seriously', 'Aim for 7–9 hours sleep and keep daily movement consistent.'],
]

const videoSearch = (query: string) => `https://www.youtube.com/results?search_query=${encodeURIComponent(`${query} proper form beginner`)}`

function App() {
  const [tab, setTab] = useState('Overview')
  const [weight, setWeight] = useState('')
  const [logs, setLogs] = useState<Log[]>(() => JSON.parse(localStorage.getItem('gainz-weights') || '[]'))
  const [workouts, setWorkouts] = useState<Workout[]>(() => JSON.parse(localStorage.getItem('gainz-workouts') || '[]'))
  const [goal, setGoal] = useState(() => localStorage.getItem('gainz-goal') || '3-day full body')
  const [profile, setProfile] = useState(() => ({ weight: localStorage.getItem('gainz-current') || '65', height: localStorage.getItem('gainz-height') || '178', activity: localStorage.getItem('gainz-activity') || 'moderate' }))
  const latest = logs.at(-1)?.weight ?? Number(profile.weight)
  const start = logs[0]?.weight ?? latest
  const gain = latest - start
  const calories = Math.round(latest * (profile.activity === 'high' ? 36 : profile.activity === 'light' ? 30 : 33) + 300)
  const protein = Math.round(latest * 1.8)
  const chart = useMemo(() => logs.slice(-7), [logs])

  function saveWeight(e: FormEvent) { e.preventDefault(); const value = Number(weight); if (!value || value < 30 || value > 300) return; const next = [...logs, { date: new Date().toISOString().slice(0, 10), weight: value }]; setLogs(next); setProfile({ ...profile, weight: String(value) }); localStorage.setItem('gainz-weights', JSON.stringify(next)); localStorage.setItem('gainz-current', String(value)); setWeight('') }
  function logWorkout() { const next = [...workouts, { date: new Date().toISOString().slice(0, 10), name: goal, exercises: plans[goal as keyof typeof plans].length, volume: Math.round(2400 + Math.random() * 900) }]; setWorkouts(next); localStorage.setItem('gainz-workouts', JSON.stringify(next)) }

  return <div className="app-shell">
    <aside className="sidebar"><div className="brand"><span className="brand-mark">↗</span><div><strong>GAINZ</strong><small>TRACKER</small></div></div><div className="profile-mini"><div className="avatar">A</div><div><strong>My bulk</strong><span>Natural progress</span></div></div><nav>{['Overview', 'Workout plan', 'Nutrition', 'Progress'].map(item => <button className={tab === item ? 'active' : ''} onClick={() => setTab(item)} key={item}><span>{item === 'Overview' ? '◈' : item === 'Workout plan' ? '✦' : item === 'Nutrition' ? '◌' : '↗'}</span>{item}</button>)}</nav><div className="sidebar-note"><span>✦</span><strong>Build patiently.</strong><p>Small surplus. Heavy basics. Consistent sleep.</p></div></aside>
    <main className="main-content"><header className="topbar"><div><p className="eyebrow">PERSONAL MUSCLE BUILDING OS</p><h1>{tab}</h1></div><div className="date-pill">● Week 1 <span>Today, {new Date().toLocaleDateString('en-US', { month: 'short', day: 'numeric' })}</span></div></header>
      {tab === 'Overview' && <><section className="hero-card"><div><span className="label">YOUR CURRENT PHASE</span><h2>Lean bulk <em>in progress.</em></h2><p>Target a steady gain of 0.25–0.5 kg per week. Train hard, eat consistently, recover.</p><button className="primary" onClick={() => setTab('Workout plan')}>View today’s session <span>→</span></button></div><div className="hero-orbit"><div className="orbit-label"><b>+{gain.toFixed(1)} kg</b><span>total change</span></div><div className="sun">↗</div></div></section><div className="section-heading"><div><span className="eyebrow">THIS WEEK</span><h2>Your signals</h2></div><button className="text-button" onClick={() => setTab('Progress')}>See progress →</button></div><section className="stats-grid"><article><span className="stat-icon green">↗</span><div><small>BODYWEIGHT</small><strong>{latest.toFixed(1)} <i>kg</i></strong><p className="positive">{gain >= 0 ? '+' : ''}{gain.toFixed(1)} kg since first log</p></div></article><article><span className="stat-icon purple">✦</span><div><small>WORKOUTS</small><strong>{workouts.length}<i> / 4</i></strong><p>{workouts.length >= 4 ? 'Target reached' : `${4 - workouts.length} left this week`}</p></div></article><article><span className="stat-icon orange">◒</span><div><small>CALORIE TARGET</small><strong>{calories.toLocaleString()}<i> kcal</i></strong><p>+300 kcal surplus</p></div></article></section><section className="lower-grid"><div className="panel progress-panel"><div className="panel-head"><div><span className="eyebrow">BODYWEIGHT</span><h2>Upward trend</h2></div><span className="green-chip">● On track</span></div><div className="mini-chart">{chart.length > 1 ? chart.map((item, i) => <div className="bar-wrap" key={i}><div className="bar" style={{ height: `${Math.max(25, ((item.weight - Math.min(...chart.map(x => x.weight)) + 1) / 3) * 100)}%` }}></div><small>{item.date.slice(5)}</small></div>) : <div className="empty-chart">Log a few weigh-ins to see your trend</div>}</div></div><div className="panel next-panel"><div className="panel-head"><div><span className="eyebrow">NEXT UP</span><h2>Today’s focus</h2></div><span className="small-arrow">→</span></div><div className="focus-row"><div className="focus-number">01</div><div><strong>{goal}</strong><p>{plans[goal as keyof typeof plans][0]}</p></div><button className="circle-button" onClick={() => setTab('Workout plan')}>→</button></div><button className="secondary full" onClick={logWorkout}>Mark workout complete</button></div></section></>}
      {tab === 'Workout plan' && <section className="content-stack"><div className="panel intro-panel"><span className="eyebrow">BEGINNER PATH · WEEKS 1–8</span><h2>Build the habit before the hype.</h2><p>Start with three repeatable full-body sessions. Learn the movements, keep 1–3 reps in reserve, and increase training volume only when recovery is good.</p><div className="starter-grid">{beginnerRules.map(([title, detail]) => <div key={title}><strong>{title}</strong><span>{detail}</span></div>)}</div></div><div className="panel"><div className="panel-head"><div><span className="eyebrow">RECOMMENDER</span><h2>Choose your rhythm.</h2></div></div><p className="muted-copy">The 3-day option is the recommended starting point. Move up only when you can recover consistently.</p><div className="plan-options">{Object.keys(plans).map(p => <button key={p} className={goal === p ? 'selected' : ''} onClick={() => { setGoal(p); localStorage.setItem('gainz-goal', p) }}><strong>{p}</strong><span>{p === '3-day full body' ? 'Recommended start' : p === '4-day upper/lower' ? 'After consistency' : 'Higher commitment'}</span></button>)}</div><a className="style-video" href={videoSearch(goal)} target="_blank" rel="noreferrer">▶ Watch a short {goal} walkthrough <span>↗</span></a></div><div className="panel"><div className="panel-head"><div><span className="eyebrow">YOUR PLAN</span><h2>{goal}</h2></div><button className="primary small" onClick={logWorkout}>Log session</button></div><div className="exercise-list">{plans[goal as keyof typeof plans].map((exercise, i) => <div className="exercise" key={exercise}><span>{String(i + 1).padStart(2, '0')}</span><div><strong>{exercise}</strong><p>3–4 sets · 6–12 reps · leave 1–3 reps in reserve</p><a href={videoSearch(exercise)} target="_blank" rel="noreferrer">▶ Watch demo</a></div><b>›</b></div>)}</div></div><div className="tip-box"><span>✦</span><div><strong>Every session has a job</strong><p>Warm up for 5–10 minutes, use controlled form, record your sets, and stop if sharp pain appears. Muscle soreness is not the goal—progress is.</p></div></div></section>}
      {tab === 'Nutrition' && <section className="content-stack"><div className="nutrition-hero"><div><span className="eyebrow">LEAN BULK NUTRITION</span><h2>Eat enough to grow.</h2><p>A small, consistent calorie surplus is the goal—not forcing huge meals or relying on a mass gainer as a meal replacement.</p></div><div className="calorie-ring"><b>{calories}</b><span>daily kcal</span></div></div><div className="macro-grid"><article><small>PROTEIN</small><strong>{protein}g</strong><p>1.6–2.2g per kg bodyweight</p></article><article><small>CARBS</small><strong>{Math.round(calories * .5 / 4)}g</strong><p>Fuel training and recovery</p></article><article><small>FATS</small><strong>{Math.round(calories * .25 / 9)}g</strong><p>Hormones and health</p></article></div><div className="panel meal-structure"><div><span className="eyebrow">SIMPLE DAILY STRUCTURE</span><h2>Make eating repeatable</h2></div><div className="meal-grid"><span>Breakfast</span><span>Protein + carbs + fruit</span><span>Lunch</span><span>Protein + rice/potatoes + vegetables</span><span>Training snack</span><span>Easy carbs + yogurt or milk</span><span>Dinner</span><span>Protein + carbs + healthy fats</span></div></div><div className="panel mass-gainer"><div className="mass-icon">+</div><div><span className="eyebrow">BEFORE YOU BUY</span><h2>Mass gainer, used wisely.</h2><p>Use it as a convenient calorie bridge when food is difficult—not as a shortcut. Start with half a serving and track it inside your daily target.</p><ul><li>Prefer clear ingredients and meaningful protein.</li><li>Take it after training or between meals; don’t replace varied whole foods.</li><li>Reduce it if digestion, appetite, or weight gain becomes uncomfortable.</li></ul></div></div><p className="disclaimer">This is general fitness guidance, not medical care. Consult a qualified professional for health conditions, allergies, or unexplained weight loss.</p></section>}
      {tab === 'Progress' && <section className="content-stack"><div className="panel log-panel"><div className="panel-head"><div><span className="eyebrow">BODYWEIGHT LOG</span><h2>Track the trend, not one day.</h2></div><form onSubmit={saveWeight} className="inline-form"><input value={weight} onChange={e => setWeight(e.target.value)} placeholder="kg" type="number" step="0.1" /><button className="primary small">Add weigh-in</button></form></div><div className="log-list">{logs.length ? [...logs].reverse().map((item, i) => <div className="log-row" key={`${item.date}-${i}`}><span>{item.date}</span><strong>{item.weight.toFixed(1)} kg</strong><em>{i === logs.length - 1 ? 'Latest' : ''}</em></div>) : <p className="empty">No weigh-ins yet. Add your first measurement above.</p>}</div></div><div className="panel"><div className="panel-head"><div><span className="eyebrow">TRAINING HISTORY</span><h2>Sessions logged</h2></div><span className="green-chip">{workouts.length} total</span></div>{workouts.length ? <div className="log-list">{[...workouts].reverse().map((w, i) => <div className="log-row" key={`${w.date}-${i}`}><span>{w.date}</span><strong>{w.name}</strong><em>{w.volume.toLocaleString()} kg volume</em></div>)}</div> : <p className="empty">Complete your first session to start your training history.</p>}</div></section>}
    </main></div>
}
export default App
